### ISSUE TITLE
Mojave Issue

### ISSUE THREAD

**Issue by HelgeKeck** [AnaghSharma/Ambar-Xamarin#7]
HI,

under mojave it isnt possible to open the settings menu

NSAppleEventDescriptor result = appleScript.ExecuteAndReturnError(out errors);

returns null

**Comment by AnaghSharma** [comment]
Hi @HelgeKeck ,

If you try to look at the errors object after you get the exception, you will see this error message - "Not authorized to send Apple events to System Events." This problem has arisen because of the new privacy features in Mojave. You cannot execute an AppleScript unless you have explicitly given permission. Since this script is related to System events, I don't know how the permission part would work. 

The whole point of running the script was to check whether the app is a part of login items of macOS or not. This helped in the checked stated of the first menu item - Launch at Login. What you can do is comment out the entire script part in the button click action. The settings menu should appear then.

**Comment by HelgeKeck** [comment]
ok, thanks a lot.
